spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    continue-on-error: 'true'
    password: ''
    initialize: 'true'
  h2:
    console:
      enabled: 'true'
      path: /h2-console

refresh-data:
  url: http://localhost:8090
  path:
    get-artists-ids: /artists
    get-tracks-ids: /tracks

mail-configuration:
  host: smtp.gmail.com
  port: 465
  socketFactory: javax.net.ssl.SSLSocketFactory
  socketFactoryPort: 465
  auth: true
  address: TESTE
  password: TESTE
  defaultMailSender: TESTE