version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

workflows:
  sample:
    jobs:
      - build-and-test
  #heroku_deploy:
    #jobs:
      #- heroku/deploy-via-git: