version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
  coverage-status:
    docker:
      - image: cimg/base:stable
    steps:
      - coveralls/upload

workflows:
  sample:
    jobs:
      - build-and-test
      - coverage-status
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          branch: /^release/*/